FROM python:3.9-slim
RUN python -m pip install poetry

COPY nsdeparturetimes /app/nsdeparturetimes
ADD poetry.lock /app/poetry.lock
ADD pyproject.toml /app/pyproject.toml

WORKDIR /app

RUN poetry install --no-dev

EXPOSE 8000

# ENTRYPOINT ["poetry", "run", "gunicorn", "-w", "4" ,"nsdeparturetimes.main:server"]